=== MaGa-UBP/UBP-PDC/workspace/Recuperatorio/JSTLEL/JSTL/JSTL-Xml/WebContent/WEB-INF/cereales.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>

    <xs:element name="cereales">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="cereal" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="cereal" type="xs:string" />

</xs:schema>

=== MaGa-UBP/UBP-PDC/workspace/Recuperatorio/JSTLEL/JSTL/JSTL-Xml/WebContent/WEB-INF/cereales.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<cereales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	      xsi:noNamespaceSchemaLocation="./cereales.xsd">
    <cereal>Cebada</cereal>
    <cereal>Avena</cereal>
    <cereal>Mijo</cereal>
    <cereal>Maíz</cereal>
    <cereal>Arroz</cereal>
    <cereal>Centeno</cereal>
    <cereal>Trigo</cereal>        
</cereales>
